### ISSUE TITLE
Employee Information

### ISSUE THREAD

**Issue by turtle11235** [turtle11235/capital-clicker#6]
Give employees names and titles.

Worker titles should all be something like Worker#XXXX
Lower Manager titles should be like Supervisor
Middle Manager titles should be random-ish combinations of [Head/Vice/Assistant/Executive] [Supervisor/President/Coordinator] of [Creativity/Products/Vision]

**Comment by cpartington** [comment]
Should worker titles be in order of hiring? If someone quits, should a newly hired worker take the same #xxxx? Or should they be random?

Should lower/middle managers have the #xxxx at the end as well?

**Comment by turtle11235** [comment]
Worker numbers should just count up from 1, no repeats even if a worker quits or is fired

LowerManagers should be titled SupervisorXXX same as the workers, but middle managers should have the random-ish titles mentioned above

Employees can have additional information like age, gender, interests, time spent in the company, etc if anyone is interested in including those things
